<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Categories.aspx.cs" Inherits="TestKnowlige.administration.Categories" %>
<%@ Register TagName="menu" TagPrefix="uc" Src="~/usercontrol/AdminMenu.ascx" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Список категорий</title>
    <link rel="Stylesheet" type="text/css" href="../style/admins.css" />
</head>
<body>
    <form id="form1" runat="server">
    <div>
    <uc:menu ID="AdminMenu" runat="server" />
        <div class="main">
            <asp:Label ID="lblHeader" Text="Список дисциплин" runat="server" />
            <asp:Label runat="server" ID="MessageError" Visible="false" CssClass="errorDelete"/>
            <asp:GridView ID="CategoriesList" runat="server"
            AutoGenerateEditButton="true" AutoGenerateDeleteButton="true"
            AutoGenerateColumns="false" 
            OnRowEditing="CategoriesList_RowEditing"
                >
                <Columns>                
                    <asp:BoundField HeaderText="Дисциплина" DataField="Discipline_name"></asp:BoundField>
                    <asp:BoundField HeaderText="Категория" DataField="Categories_name"></asp:BoundField>
                     <asp:TemplateField HeaderText="Дисциплина">
                    <EditItemTemplate>
                        <asp:DropDownList ID="DropDownDiscipline" runat="server" 
                            DataTextField="Дисциплина" DataValueField="Discipline_name"                             
                            >
                        </asp:DropDownList>
                    </EditItemTemplate>                    
                </asp:TemplateField>
                </Columns>
                
            <EditRowStyle Font-Bold="True"/>    
            </asp:GridView>
        </div>     
    </div>
    </form>
</body>
</html>
