<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Disciplines.aspx.cs" Inherits="TestKnowlige.administration.Disciplines" %>
<%@ Register TagName="menu" TagPrefix="uc" Src="~/usercontrol/AdminMenu.ascx" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Список дисциплин</title>
    <link rel="Stylesheet" type="text/css" href="../style/admins.css" />
</head>
<body>
    <form id="form1" runat="server">
    <div>
        <uc:menu ID="AdminMenu" runat="server" />
        <div class="main">
            <asp:Label ID="lblHeader" Text="Список дисциплин" runat="server" />
            <asp:Label runat="server" ID="MessageError" Visible="false" CssClass="errorDelete"/>
            <asp:GridView ID="DisciplineList" runat="server"
            AutoGenerateEditButton="true" AutoGenerateDeleteButton="true"
            AutoGenerateColumns="false" 
            OnRowEditing="Disciplinelist_RowEditing"
            OnRowCancelingEdit="Disciplinelist_RowCancelEditing"
            OnRowUpdating="Disciplinelist_RowUpdating"
            OnRowDeleting="Disciplinelist_RowDeleting"           
            >
                <Columns>
                    <asp:BoundField HeaderText="Название" DataField="Discipline_name"></asp:BoundField>
            </Columns>
            <EditRowStyle Font-Bold="True" />    
            </asp:GridView>
        </div> 
    
    </div>
    </form>
</body>
</html>
