<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Tests.aspx.cs" Inherits="TestKnowlige.administration.Tests" %>
<%@ Register TagName="menu" TagPrefix="uc" Src="~/usercontrol/AdminMenu.ascx" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Список тестов тесты</title>
    <link rel="Stylesheet" type="text/css" href="../style/admins.css" />
</head>
<body>
    <form id="form1" runat="server">
    <div>
     <uc:menu ID="AdminMenu" runat="server" />
        <div class="main">
            <asp:Label ID="lblHeader" Text="Список тестов" runat="server" />
            <asp:Label runat="server" ID="MessageError" Visible="false" CssClass="error"/>
            <asp:GridView ID="TestList" runat="server"
            AutoGenerateEditButton="true" AutoGenerateDeleteButton="true"
            AutoGenerateColumns="false"              
            OnRowEditing="TestList_RowEditing"                     
            OnRowCancelingEdit="TestList_CancelingEdit"
            OnRowUpdating="TestList_UpdatingRow"
            OnRowDeleting="TestList_RowDeleting"                       
                >
                <Columns>
                    <asp:TemplateField HeaderText = "Дисциплина">
                    <ItemTemplate>
                            <asp:Label ID="lblDiscipline_name" runat="server" Text='<%# Eval("Discipline_name") %>' />                                                        
                     </ItemTemplate>
                    <EditItemTemplate>
                        <asp:DropDownList runat="server" ID="ddDiscipline"  
                            DataTextField="Discipline_Name"  AutoPostBack="true" OnSelectedIndexChanged="ddDiscipline_ChangeIndex"
                            DataValueField="Discipline_Name">                            
                        </asp:DropDownList>                        
                    </EditItemTemplate>                        
                    </asp:TemplateField>                    
                </Columns>    
                <Columns>
                    <asp:TemplateField HeaderText = "Категория">
                    <ItemTemplate>
                            <asp:Label ID="lblCategories_name" runat="server" Text='<%# Eval("Categories_name") %>' />
                     </ItemTemplate>
                    <EditItemTemplate>
                        <asp:DropDownList runat="server" ID="ddCategories"  
                            DataTextField="Categories_Name" 
                            DataValueField="Categories_Name">                            
                        </asp:DropDownList>                        
                    </EditItemTemplate>                        
                    </asp:TemplateField>                    
                </Columns>    
                <Columns>                    
                    <asp:TemplateField HeaderText="Тест">
                            <ItemTemplate> 
                                <asp:Label Text='<%# Eval("name") %>' runat="server" />
                            </ItemTemplate>                        
                             <EditItemTemplate>
                                 <asp:TextBox runat="server" Text='<%# Eval("name") %>' ID="TestName"/>
                            </EditItemTemplate>   
                    </asp:TemplateField>                    
                </Columns>    
                <Columns>
                    <asp:TemplateField HeaderText="Редактировать тест">
                        <ItemTemplate> 
                            <asp:HyperLink ReadOnly="True" ID="TestEditLink" NavigateUrl='<%# "~/profile/Teacher/TestEdit.aspx?id="+Eval("test_id") %>' runat="server" Text="Редактировать" Target="_blank"/>
                        </ItemTemplate>                        
                    </asp:TemplateField>
                </Columns>
            </asp:GridView>
        </div>   
    </div>
    </form>
</body>
</html>
